drop table TBL_BATCH_LOG_DETAILS;
drop table TBL_BATCH_LOG;

SET SQL_MODE = 'ALLOW_INVALID_DATES';

CREATE TABLE
IF
	NOT EXISTS TBL_BATCH_LOG_DETAILS (
		ID INT AUTO_INCREMENT NOT NULL,
		BATCH_ID INT,
		BATCH_NO VARCHAR ( 128 ),
		JOB_NAME VARCHAR ( 256 ),
		JOB_STATUS VARCHAR ( 20 ),
		JOB_INDEX INT,
		MSG VARCHAR ( 2048 ),
		SAVE_POINT VARCHAR ( 200 ),
		CREATE_TIME TIMESTAMP,
		START_TIME TIMESTAMP,
		UPDATE_TIME TIMESTAMP,
		PRIMARY KEY ( ID ) 
	) ;
	
	CREATE TABLE
IF
	NOT EXISTS TBL_BATCH_LOG (
		ID INT AUTO_INCREMENT NOT NULL,
		BATCH_NO VARCHAR ( 128 ),
		BATCH_STATUS VARCHAR ( 20 ),
		BATCH_NAME VARCHAR ( 128 ),
		FAILURE_INDEX INT,
		CREATE_TIME TIMESTAMP,
		START_TIME TIMESTAMP,
		UPDATE_TIME TIMESTAMP,
		EXECUTE_DATE VARCHAR ( 128 ),
		MSG VARCHAR ( 2048 ),
	PRIMARY KEY ( ID ) 
	)